name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.0]

    steps:
      - uses: actions/checkout@v3
      - name: starting Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm ci
      - name: build production project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run style
      - name: unit testing
        run: npm run unit
      - name: build storybook
        run: npm run build-storybook
      - name: screenshot testing
        run: npm run test:ui:ci